HamburgerAppV1/Areas/Admin/Controllers/DashboardController.cs
using HamburgerAppV1.Areas.Admin.Models;
using HamburgerAppV1.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SQLitePCL;

namespace HamburgerAppV1.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator")]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;

        public DashboardController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _db = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {

            var dashboard = new DashboardViewModel
            {
                EnCokSiparisEdilenMenuler = GetEnCokSiparisEdilenMenuler(),
                EnCokKullanilanEkstraMalzemeler = GetEnCokKullanilanEkstraMalzemeler()
            };

            return View(dashboard);
        }

        public IActionResult EnCokSiparisEdilenMenuler()
        {
            var enCokSiparisEdilenMenuler = GetEnCokSiparisEdilenMenuler();
            var viewModel = new DashboardViewModel
            {
                EnCokSiparisEdilenMenuler = enCokSiparisEdilenMenuler,
                EnCokKullanilanEkstraMalzemeler = new List<EnCokKullanilanEkstraMalzemeModel>()
            };
            return View(viewModel);
        }

        public IActionResult EnCokKullanilanEkstraMalzemeler()
        {
            var enCokKullanilanEkstraMalzemeler = GetEnCokKullanilanEkstraMalzemeler();
            var viewModel = new DashboardViewModel
            {
                EnCokSiparisEdilenMenuler = new List<EnCokSiparisEdilenMenuModel>(),
                EnCokKullanilanEkstraMalzemeler = enCokKullanilanEkstraMalzemeler
            };
            return View(viewModel);
        }

        public async Task<IActionResult> KayitliKullanicilar()
        {
            var kullanici = await _userManager.GetUserAsync(User);

            var applicationDbContext = _db.Siparisler
                .Include(s => s.Kullanici)
                .Where(s => s.IdentityUserId != null)
                .Select(s => s.Kullanici)
                .Distinct();

            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> TumSiparisler()
        {
            var siparisler = await _db.Siparisler
                .Include(s => s.Kullanici)
                .Include(s => s.Menu)
                .Include(s => s.EkstraMalzemeler)
                .ToListAsync();

            return View(siparisler);

        }

        private List<EnCokSiparisEdilenMenuModel> GetEnCokSiparisEdilenMenuler()
        {
            return _db.Siparisler
                .GroupBy(s => s.Menu.MenuAd)
                .OrderByDescending(grp => grp.Count())
                .Select(grp => new EnCokSiparisEdilenMenuModel
                {
                    MenuAdi = grp.Key,
                    SiparisSayisi = grp.Count()
                })
                .ToList();
        }

        private List<EnCokKullanilanEkstraMalzemeModel> GetEnCokKullanilanEkstraMalzemeler()
        {
            return _db.Siparisler
                .SelectMany(s => s.EkstraMalzemeler)
                .GroupBy(em => em.EktraMalzemeAd)
                .OrderByDescending(grp => grp.Count())
                .Select(grp => new EnCokKullanilanEkstraMalzemeModel
                {
                    MalzemeAdi = grp.Key,
                    KullanilmaSayisi = grp.Count()
                })
                .ToList();
        }
    }
}

HamburgerAppV1/Areas/Musteri/Controllers/SiparisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HamburgerAppV1.Data;
using HamburgerAppV1.Entities;
using HamburgerAppV1.Enums;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel.DataAnnotations;

namespace HamburgerAppV1.Areas.Musteri.Controllers
{
    [Area("Musteri")]
    [Authorize(Roles = "Musteri")]
    public class SiparisController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public SiparisController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> MenuleriIncele()
        {
            return View(await _context.Menuler.ToListAsync());
        }

        // GET: Musteri/Siparis
        public async Task<IActionResult> Index()
        {
            var kullanici = await _userManager.GetUserAsync(User);

            var applicationDbContext = _context.Siparisler
                .Include(s => s.Kullanici)
                .Include(s => s.Menu)
                .Include(s => s.EkstraMalzemeler)
                .Where(s => s.IdentityUserId == kullanici.Id);

            return View(await applicationDbContext.ToListAsync());
        }


        public async Task<IActionResult> SiparisBilgileri(Siparis siparis, List<int> ekstraMalzemeler)
        {
            return View(siparis);
        }


        [HttpPost]
        public IActionResult SiparisBilgileri()
        {
            return RedirectToAction("MenuleriIncele");
        }


        // GET: Musteri/Siparis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var siparis = await _context.Siparisler
                .Include(s => s.Kullanici)
                .Include(s => s.Menu)
                .Include(s => s.EkstraMalzemeler)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (siparis == null)
            {
                return NotFound();
            }

            return View(siparis);
        }

        // GET: Musteri/Siparis/Create
        public IActionResult Create()
        {
            ViewBag.Menuler = _context.Menuler.ToList();
            ViewBag.Boyutlar = Enum.GetValues(typeof(MenuBoyutu))
                    .Cast<MenuBoyutu>()
                    .Select(e => new SelectListItem
                    {
                        Value = e.ToString(),
                        Text = GetEnumDisplayName(e)
                    })
                    .ToList();

            ViewBag.EkstraMalzemeler = _context.EkstraMalzemeler.ToList();

            return View();
        }


        private string GetEnumDisplayName(Enum value)
        {
            var field = value.GetType().GetField(value.ToString());
            var attribute = (DisplayAttribute)field.GetCustomAttributes(typeof(DisplayAttribute), false).FirstOrDefault();
            return attribute == null ? value.ToString() : attribute.GetName();
        }


        // POST: Musteri/Siparis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Siparis siparis, List<int> ekstraMalzemeler)
        {
            ViewBag.Menuler = _context.Menuler.ToList();
            ViewBag.Boyutlar = Enum.GetValues(typeof(MenuBoyutu)).Cast<MenuBoyutu>().Select(e => new SelectListItem { Value = e.ToString(), Text = Enum.GetName(typeof(MenuBoyutu), e) }).ToList();
            ViewBag.EkstraMalzemeler = _context.EkstraMalzemeler.ToList();


            if (siparis.MenuId == 0)
            {
                TempData["Hata"] = "Lütfen Menü Seçiniz";

                return View();
            }

            var menu = _context.Menuler.Find(siparis.MenuId);

            siparis.Menu = menu;
            siparis.EkstraMalzemeler = _context.EkstraMalzemeler.Where(e => ekstraMalzemeler.Contains(e.Id)).ToList();
            siparis.SiparisTarihi = DateTime.Now;
            siparis.IdentityUserId = _userManager.GetUserId(User);
            siparis.Kullanici = _userManager.GetUserAsync(User).Result; // Bu satırda `.Result` kullanarak asenkron beklemeyi sağlıyoruz.

            siparis.Hesapla();

            if (siparis != null)
            {

                _context.Siparisler.Add(siparis);
                _context.SaveChanges();

                return View("SiparisBilgileri", siparis);
            }



            return View(siparis);
        }


        //// GET: Musteri/Siparis/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var siparis = await _context.Siparisler.FindAsync(id);
        //    if (siparis == null)
        //    {
        //        return NotFound();
        //    }

        //    ViewBag.Menuler = _context.Menuler.ToList();
        //    ViewBag.Boyutlar = Enum.GetValues(typeof(MenuBoyutu)).Cast<MenuBoyutu>().Select(e => new SelectListItem { Value = e.ToString(), Text = Enum.GetName(typeof(MenuBoyutu), e) }).ToList();
        //    ViewBag.EkstraMalzemeler = _context.EkstraMalzemeler.ToList();

        //    return View(siparis);
        //}

        // POST: Musteri/Siparis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, Siparis siparis, List<int> ekstraMalzemeler)
        //{
        //    if (id != siparis.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            var menu = await _context.Menuler.FindAsync(siparis.MenuId);
        //            if (menu == null)
        //            {
        //                TempData["Hata"] = "Lütfen Menü Seçiniz.";
        //                return View(siparis);
        //            }

        //            siparis.Menu = menu;
        //            siparis.EkstraMalzemeler = _context.EkstraMalzemeler.Where(e => ekstraMalzemeler.Contains(e.Id)).ToList();
        //            siparis.SiparisTarihi = DateTime.Now;
        //            siparis.IdentityUserId = _userManager.GetUserId(User);
        //            siparis.Kullanici = await _userManager.GetUserAsync(User);

        //            _context.Update(siparis);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!SiparisExists(siparis.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewBag.Menuler = _context.Menuler.ToList();
        //    ViewBag.Boyutlar = Enum.GetValues(typeof(MenuBoyutu)).Cast<MenuBoyutu>().Select(e => new SelectListItem { Value = e.ToString(), Text = Enum.GetName(typeof(MenuBoyutu), e) }).ToList();
        //    ViewBag.EkstraMalzemeler = _context.EkstraMalzemeler.ToList();
        //    return View(siparis);
        //}

        // GET: Musteri/Siparis/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var siparis = await _context.Siparisler
                .Include(s => s.Kullanici)
                .Include(s => s.Menu)
                .Include(s => s.EkstraMalzemeler)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (siparis == null)
            {
                return NotFound();
            }

            return View(siparis);
        }

        // POST: Musteri/Siparis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var siparis = await _context.Siparisler.FindAsync(id);
            if (siparis != null)
            {
                _context.Siparisler.Remove(siparis);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SiparisExists(int id)
        {
            return _context.Siparisler.Any(e => e.Id == id);
        }
    }
}

HamburgerAppV1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using HamburgerAppV1.Data
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hamburgerci</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body style="background-color: rgb(179, 163, 152)">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand fs-3 fw-bold" style="color: rgb(255, 217, 102)" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo.png" width="100px" alt="" />
                    Hamburgerci
                </a>

                <a class="navbar-brand fs-5 fw-bold" style="color: rgb(255, 217, 102)" asp-area="" asp-controller="Home" asp-action="Hakkimizda">
                    Hakkımızda
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                    </ul>

                    @if (SignInManager.IsSignedIn(User))
                    {
                        if (User.IsInRole("Administrator"))
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item me-2">
                                    <a class="nav-link btn btn-outline-light rounded-2 fw-bold" style="color: rgb(255, 217, 102)" asp-area="Admin"
                                       asp-action="Index" asp-controller="Dashboard">Yönetici Paneli</a>
                                </li>
                            </ul>

                        }
                        else
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item me-2">
                                    <a class="nav-link rounded-2 fw-bold btn btn-outline-light" style="color:rgb(255, 217, 102)"
                                       asp-action="MenuleriIncele" asp-controller="Siparis" asp-area="Musteri">Sipariş Verin</a>
                                </li>
                                <li class="nav-item me-2">
                                    <a class="nav-link rounded-2 fw-bold btn btn-outline-light" style="color:rgb(255, 217, 102)"
                                       asp-action="Index" asp-controller="Siparis" asp-area="Musteri">Siparişlerim</a>
                                </li>
                            </ul>
                        }

                        <partial name="_LoginPartial" />
                    }
                    else
                    {
                        <partial name="_LoginPartial" />
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid mb-auto">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
    <div class="container">
    Copyright &copy; Hamburgerci 2024
    </div>
    </footer> *@
    <footer class="footer py-5 mt-auto">

        <div class="container"><p class="m-0 text-center" style="color: rgb(255, 217, 102)"><b>Copyright &copy; Hamburgerci 2024</b></p></div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>