HamburgerAppV1/Areas/Admin/Controllers/DashboardController.cs
using HamburgerAppV1.Areas.Admin.Models;
using HamburgerAppV1.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SQLitePCL;

namespace HamburgerAppV1.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator")]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;

        public DashboardController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _db = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {

            var dashboard = new DashboardViewModel
            {
                EnCokSiparisEdilenMenuler = GetEnCokSiparisEdilenMenuler(),
                EnCokKullanilanEkstraMalzemeler = GetEnCokKullanilanEkstraMalzemeler()
            };

            return View(dashboard);
        }

        public IActionResult EnCokSiparisEdilenMenuler()
        {
            var enCokSiparisEdilenMenuler = GetEnCokSiparisEdilenMenuler();
            var viewModel = new DashboardViewModel
            {
                EnCokSiparisEdilenMenuler = enCokSiparisEdilenMenuler,
                EnCokKullanilanEkstraMalzemeler = new List<EnCokKullanilanEkstraMalzemeModel>()
            };
            return View(viewModel);
        }

        public IActionResult EnCokKullanilanEkstraMalzemeler()
        {
            var enCokKullanilanEkstraMalzemeler = GetEnCokKullanilanEkstraMalzemeler();
            var viewModel = new DashboardViewModel
            {
                EnCokSiparisEdilenMenuler = new List<EnCokSiparisEdilenMenuModel>(),
                EnCokKullanilanEkstraMalzemeler = enCokKullanilanEkstraMalzemeler
            };
            return View(viewModel);
        }

        public async Task<IActionResult> KayitliKullanicilar()
        {
            var kullanici = await _userManager.GetUserAsync(User);

            var applicationDbContext = _db.Siparisler
                .Include(s => s.Kullanici)
                .Where(s => s.IdentityUserId != null)
                .Select(s => s.Kullanici)
                .Distinct();

            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> TumSiparisler()
        {
            var siparisler = await _db.Siparisler
                .Include(s => s.Kullanici)
                .Include(s => s.Menu)
                .Include(s => s.EkstraMalzemeler)
                .ToListAsync();

            return View(siparisler);

        }

        private List<EnCokSiparisEdilenMenuModel> GetEnCokSiparisEdilenMenuler()
        {
            return _db.Siparisler
                .GroupBy(s => s.Menu.MenuAd)
                .OrderByDescending(grp => grp.Count())
                .Select(grp => new EnCokSiparisEdilenMenuModel
                {
                    MenuAdi = grp.Key,
                    SiparisSayisi = grp.Count()
                })
                .ToList();
        }

        private List<EnCokKullanilanEkstraMalzemeModel> GetEnCokKullanilanEkstraMalzemeler()
        {
            return _db.Siparisler
                .SelectMany(s => s.EkstraMalzemeler)
                .GroupBy(em => em.EktraMalzemeAd)
                .OrderByDescending(grp => grp.Count())
                .Select(grp => new EnCokKullanilanEkstraMalzemeModel
                {
                    MalzemeAdi = grp.Key,
                    KullanilmaSayisi = grp.Count()
                })
                .ToList();
        }
    }
}

HamburgerAppV1/Areas/Admin/Controllers/EkstraMalzemeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HamburgerAppV1.Data;
using HamburgerAppV1.Entities;
using Microsoft.AspNetCore.Authorization;

namespace HamburgerAppV1.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator")]

    public class EkstraMalzemeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EkstraMalzemeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/EkstraMalzeme
        public async Task<IActionResult> Index()
        {           
            return View(await _context.EkstraMalzemeler.ToListAsync());
        }

        // GET: Admin/EkstraMalzeme/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var ekstraMalzeme = await _context.EkstraMalzemeler
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (ekstraMalzeme == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(ekstraMalzeme);
        //}

        // GET: Admin/EkstraMalzeme/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/EkstraMalzeme/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EktraMalzemeAd,EktraMalzemeFiyat")] EkstraMalzeme ekstraMalzeme)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ekstraMalzeme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ekstraMalzeme);
        }

        // GET: Admin/EkstraMalzeme/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ekstraMalzeme = await _context.EkstraMalzemeler.FindAsync(id);
            if (ekstraMalzeme == null)
            {
                return NotFound();
            }
            return View(ekstraMalzeme);
        }

        // POST: Admin/EkstraMalzeme/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EktraMalzemeAd,EktraMalzemeFiyat")] EkstraMalzeme ekstraMalzeme)
        {
            if (id != ekstraMalzeme.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ekstraMalzeme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EkstraMalzemeExists(ekstraMalzeme.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ekstraMalzeme);
        }

        // GET: Admin/EkstraMalzeme/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ekstraMalzeme = await _context.EkstraMalzemeler
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ekstraMalzeme == null)
            {
                return NotFound();
            }

            return View(ekstraMalzeme);
        }

        // POST: Admin/EkstraMalzeme/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ekstraMalzeme = await _context.EkstraMalzemeler.FindAsync(id);
            if (ekstraMalzeme != null)
            {
                _context.EkstraMalzemeler.Remove(ekstraMalzeme);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EkstraMalzemeExists(int id)
        {
            return _context.EkstraMalzemeler.Any(e => e.Id == id);
        }
    }
}

HamburgerAppV1/Areas/Admin/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HamburgerAppV1.Data;
using HamburgerAppV1.Entities;
using Microsoft.AspNetCore.Authorization;
using HamburgerAppV1.Models;

namespace HamburgerAppV1.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator")]

    public class MenuController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly Menu _menu;

        public MenuController(ApplicationDbContext context, Menu menu)
        {
            _context = context;
            _menu = menu;
        }

        // GET: Admin/Menu
        public async Task<IActionResult> Index()
        {
            return View(await _context.Menuler.ToListAsync());
        }

        // GET: Admin/Menu/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menuler
                .FirstOrDefaultAsync(m => m.Id == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // GET: Admin/Menu/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Menu/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MenuViewModel menuViewModel)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    //Fiyatın pozitif olması durumu
                    if (menuViewModel.MenuFiyat <= 0)
                        throw new Exception("Fiyat pozitif olmalıdır!");

                    //Aynı ürün isminden başka veremesin.
                    if (_context.Menuler.FirstOrDefault(u => u.MenuAd == menuViewModel.MenuAd) != null)
                        throw new Exception("Eklemek istediğiniz ürün mevcuttur!");

                    //Kişi resim yüklemek zorunda DEĞİL!
                    if (menuViewModel.Resim != null) //kişi resim seçtiyse
                    {
                        var dosyaAdi = menuViewModel.Resim.FileName;

                        var konum = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", dosyaAdi);

                        var akisOrtami = new FileStream(konum, FileMode.Create);

                        menuViewModel.Resim.CopyTo(akisOrtami);

                        akisOrtami.Close();

                        _menu.ResimYolu = dosyaAdi;
                    }

                    _menu.MenuAd = menuViewModel.MenuAd;
                    _menu.MenuFiyat = menuViewModel.MenuFiyat;

                    //Db'ye ekle
                    _context.Menuler.Add(_menu);
                    _context.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View();

            }
            catch (Exception ex)
            {
                TempData["Durum"] = "Hata oluştu! " + ex.Message;
                return View();
            }
        }

        // GET: Admin/Menu/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Menu guncellenecekMenu = await _context.Menuler.FindAsync(id);

            MenuViewModel guncellenecekVm = new MenuViewModel();

            if (guncellenecekMenu == null)
            {
                return NotFound();
            }

            guncellenecekVm.MenuAd = guncellenecekMenu.MenuAd;
            guncellenecekVm.MenuFiyat = guncellenecekMenu.MenuFiyat;

            TempData["Id"] = guncellenecekMenu.Id;

            return View(guncellenecekVm);
        }

        // POST: Admin/Menu/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MenuViewModel menuViewModel)
        {

            var guncellenecekMenu = _context.Menuler.Find(TempData["Id"]);

            if (ModelState.IsValid)
            {
                try
                {

                    //Fiyatın pozitif olması durumu
                    if (menuViewModel.MenuFiyat <= 0)
                        throw new Exception("Fiyat pozitif olmalıdır!");

                    //Aynı ürün isminden başka veremesin.
                    if (_context.Menuler.FirstOrDefault(u => u.MenuAd == menuViewModel.MenuAd && u.Id != guncellenecekMenu.Id) != null)
                        throw new Exception("Güncellemek istediğiniz ürün ismi mevcuttur!");



                    //Kişi resim yüklemek zorunda DEĞİL!
                    if (menuViewModel.Resim != null && menuViewModel.Resim.FileName != guncellenecekMenu.ResimYolu) //kişi resim seçtiyse
                    {
                        ResimSil(guncellenecekMenu);

                        var dosyaAdi = menuViewModel.Resim.FileName;

                        var konum = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", dosyaAdi);

                        var akisOrtami = new FileStream(konum, FileMode.Create);

                        menuViewModel.Resim.CopyTo(akisOrtami);

                        akisOrtami.Close();

                        guncellenecekMenu.ResimYolu = dosyaAdi;
                    }

                    guncellenecekMenu.MenuAd = menuViewModel.MenuAd;
                    guncellenecekMenu.MenuFiyat = menuViewModel.MenuFiyat;

                    _context.Menuler.Update(guncellenecekMenu);
                    _context.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["Durum"] = "Hata oluştu! " + ex.Message;
                    return View();
                }

            }
            return View();

        }

        // GET: Admin/Menu/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menuler
                .FirstOrDefaultAsync(m => m.Id == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // POST: Admin/Menu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var menu = await _context.Menuler.FindAsync(id);
            if (menu != null)
            {
                _context.Menuler.Remove(menu);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MenuExists(int id)
        {
            return _context.Menuler.Any(e => e.Id == id);
        }

        public void ResimSil(Menu menu)
        {
            var resmiKullananBaskaVarMi = _context.Menuler.Any(u => u.ResimYolu == menu.ResimYolu && u.Id != menu.Id);

            if (menu.ResimYolu != null && !resmiKullananBaskaVarMi)
            {
                string dosya = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", menu.ResimYolu);

                //Silme metoduna bu patikayı gönder.
                System.IO.File.Delete(dosya);
            }

        }
    }
}

HamburgerAppV1/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title - Hamburgerci Administrator</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/Admin/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" asp-area="" asp-controller="Home" asp-action="Index">Hamburgerci</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">                                     
                    <form id="Cikis" class="form-inline btn btn-outline-light rounded-2 fw-bold" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <li><a class="dropdown-item" href="#" onclick="document.getElementById('Cikis').submit(); return false;">Çıkış Yap</a></li>
                    </form>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Yönetim Paneli</div>
                        <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Ana Sayfa
                        </a>
                        <div class="sb-sidenav-menu-heading">Sipariş Yönetimi</div>
                        <a class="nav-link" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Menüler
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse show" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Menu" asp-action="Index">Listele</a>
                                <a class="nav-link" asp-controller="Menu" asp-action="Create">Ekle</a>

                            </nav>
                        </div>
                        <a class="nav-link" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePosts" aria-expanded="false" aria-controls="collapsePosts">
                            <div class="sb-nav-link-icon"><i class="fas fa-newspaper"></i></div>
                            Ekstra Malzemeler
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse show" id="collapsePosts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="EkstraMalzeme" asp-action="Index">Listele</a>
                                <a class="nav-link" asp-controller="EkstraMalzeme" asp-action="Create">Ekle</a>

                            </nav>
                        </div>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    @User.Identity!.Name
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <h1 class="mt-2">@ViewBag.Title</h1>
                    @RenderBody()
                </div>
            </main>
            
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/admin/js/scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("scripts", false)
</body>
</html>